# Generated by Django 3.1 on 2020-08-07 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0002_auto_20200807_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='username',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
